[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
